### ISSUE TITLE
Are there code repo for dbx, instead of only providing as a wheel

### ISSUE THREAD

**Issue by dexianta** [databrickslabs/cicd-templates#25]

**Comment by renardeinside** [comment]
Hi @dexianta , this repository is currently in private mode, but we have a plan to make it open-sourced as well. I would say that timeline is the end of 2020, but this could be stretched due to the review process.

**Comment by dexianta** [comment]
Hi @renardeinside , thank you for the reply, and thank you for the big revamp of the previous code!

I'm seeing that in the `dbx` code, under `utils/common.py at line 131`, 1.2 version of the rest api is used instead of 2.0, may I ask what's the motivation behind?

Thank you

**Comment by renardeinside** [comment]
[V1.2 API](https://docs.databricks.com/dev-tools/api/1.2/index.html) is used only for `dbx execute`, the reason is that we need to execute some code on an interactive cluster, without creating a new job to avoid package version override across multiple users of the same cluster. For this purpose, we're using [execution context](https://docs.databricks.com/dev-tools/api/1.2/index.html#execution-context) API methods.
